services:
  main:
    build: .
    volumes:
      - .:/app  # Mount the current directory into the container
      - /app/node_modules  # Prevent node_modules from being overwritten by the host
    ports:
      - "8080:8080"  # Expose port
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file system changes inside Docker