name: Build

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    lint:
        name: Run ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install dependencies
              run: npm install
            - name: Run ESLint
              run: npx eslint .

    test:
        needs: lint
        name: Run vitest
        runs-on: ubuntu-latest
        env:
            VITE_USE_LOCAL_DATA: 'true'
            VITE_APP_AUTH_API_URL: 'http://test-auth-api.com/'
            VITE_APP_FETCH_GENERAL_API_URL: 'http://test-api.com/'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install dependencies
              run: npm install
            - name: Run vitest
              run: npm run test

    build_and_deploy_job:
        needs: test
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Deploy to Azure
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_MUD_0EE2D5A03 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'dist' # Built app content directory - optional
                  ###### End of Repository/Build Configurations ######
              env:
                  VITE_USE_LOCAL_DATA: 'false'
                  VITE_APP_FETCH_GENERAL_API_URL: 'https://api.voya-trips.com/'
                  VITE_APP_AUTH_API_URL: 'https://auth.voya-trips.com/'

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_MUD_0EE2D5A03 }}
                  action: 'close'

    deploy:
        name: Deploy dev container
        runs-on: ubuntu-latest
        needs: test
        if: github.event_name == 'push' && contains(github.ref, 'main')
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ secrets.GH_DEPLOYER }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ghcr.io/travelator/travelator-app:latest
